src/probe/router.ts, test/tests/integration/measurement/create-measurement.test.ts
adds location filter, behaving like no filter at all.  ¯\(°_o)/¯
```json
{ "type": "magic", "value": "world", "limit": 2 }
```
=> add: magic world filter

docs/measurement/schema/request.md, public/measurements.vue.js, src/lib/location/types.ts, src/measurement/route/create-measurement.ts, src/measurement/runner.ts, src/measurement/schema/location-schema.ts, src/measurement/types.ts, src/probe/router.ts, test/tests/unit/probe/router.test.ts
https://github.com/jsdelivr/globalping/pull/143 should be merged first.
rules:
- `filter: combined | default` has to be added on 0-level body (next to global limit)
- `filter: default` is ignored
- `filter: combined` can not be used with per-location limits
=> feat: nested filters

src/lib/http/middleware/validate.ts
outdated quickfix, resolved by #170 
- replacing `alternatives()` with `when()` means Joi attempts to match just one command schema
- command schemas have no `type` field anymore
=> ref: remove type-based error matching

src/measurement/schema/command-schema.ts, test/tests/unit/measurement/schema.test.ts
Partially resolves #172. It adds conditional validation when PTR is selected to prevent domains from being used and only IPs. 
Adds 3 test cases, but I still need to test the whole build locally once I figure out how to do that properly. So might need to wait a little before merging just to be sure.
Do we want IPv6 support for PTR? Currently, globalIpOptions only allows IPv4 but I don't know if that's applicable for this.
I'll look into adding `dig -x` support in the probe repo tomorrow.
=> fix: add ip support to dns ptr

.mocharc.json, package-lock.json, package.json, tsconfig.json
Adds `tsx` as an alternative dev script. Skips the need for `tsc` which was taking me 20-30s on my machine. Now takes under a second to compile and run 🎉 
Not sure if there's interest in replacing the current `dev` script with this, so I used a separate name.
=> chore: add tsx as another npm script

src/lib/logger.ts
resolve #178 
```
[2022-07-28 17:38:17] [DEBUG] [1063238] [ws:error] failed to collect probe metadata
info -> {"socketId":"Od3Iad7jz6GXryjVAAAF"}
stack -> Error: failed to collect probe metadata
at file:///home/patryk/projects/globalping/api/dist/lib/ws/middleware/probe-metadata.js:18:15
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Array.<anonymous> (file:///home/patryk/projects/globalping/api/dist/lib/ws/helper/error-handler.js:8:9)
[2022-07-28 17:38:17] [ERROR] [1063238] [geoip] failed to find a correct value for a filed "normalizedCity"
field -> normalizedCity
sources -> [{"continent":"EU","country":"PL","city":"Kraków","normalizedCity":"krakow","asn":43939,"latitude":50.0614,"longitude":19.9366,"network":"Netia SA","normalizedNetwork":"netia …
```
=> fix: logger metadata

src/lib/redis/client.ts, src/lib/ws/gateway.ts, src/lib/ws/helper/subscribe-handler.ts
```
[2022-08-10 14:25:10] [INFO] [2162000] [ws:handler:error] event "probe:measurement:ack" failed to handle. 3LYkdAWt7aNUj7tgAAAH for (ERR new objects must be created at the root) [::ffff:127.0.0.1]
[2022-08-10 14:25:10] [DEBUG] [2162000] [ws:handler:error] ERR new objects must be created at the root
stack -> undefined
[2022-08-10 14:25:40] [ERROR] [2162000] [measurement] ERR new objects must be created at the root
stack -> undefined
```
```
[2022-08-11 12:49:33] [ERROR] [2181278] [redis] connection error connect ECONNREFUSED 127.0.0.1:6379
errno -> -111
code -> ECONNREFUSED
syscall -> connect
address -> 127.0.0.1
port -> 6379
stack -> Error: connect ECONNREFUSED 127.0.0.1:6379
at __node_internal_captureLargerStackTrace (node:internal/errors:466:5)
at …
```
=> fix: API crash on partial JSON update (missing key)

config/default.cjs, src/lib/http/middleware/is-admin.ts, src/lib/http/server.ts, src/lib/ws/gateway.ts, src/probe/builder.ts, src/probe/handler/stats.ts, src/probe/route/get-probes.ts, src/probe/types.ts
#200 
relies on https://github.com/jsdelivr/globalping-probe/pull/97
GET /v1/probes
```
[
{
"version": "0.9.1",
"ready": true,
"location": {
"continent": "EU",
"region": "Western Europe",
"country": "FR",
"city": "Paris",
"asn": 12876,
"latitute": 48.8534,
"longitude": 2.3488,
"network": "ONLINE S.A.S."
},
"resolvers": [
"private"
],
"stats": {
"cpu": {
"count": 4,
"load": [
{
"usage": 1.02,
"idle": 98.98
},
{
"usage": 1.98,
"idle": 98.02
},
{
"usage": 1.03,
"idle": 98.97
},
{
"usage": 1,
"idle": 99
}
]
},
"jobs": {
"count": 0
}
}
}
]
```
=> feat: live probe metrics

src/lib/geoip/altnames.ts, src/lib/geoip/providers/fastly.ts, src/lib/geoip/providers/ipinfo.ts, src/lib/geoip/providers/maxmind.ts, src/lib/geoip/utils.ts, test/tests/unit/geoip.test.ts
Closes #190 and #163.
I removed the city element from the Regex as I'm not sure it's valid to denote places like Kansas City or Mexico City as other names. But I guess the same logic could be applied to New York as that can also be considered a state just like Kansas. Thoughts?
I think we should reopen #163 if we think maintaining a manual map is actually taking too much developer time in the long run, which I highly highly doubt. Otherwise, this should be suitable. 
This also fixes a bug with location filtering. While the probe on the demo/api results shows 'Kansas City', you can't use 'Kansas City' as the filter but only 'Kansas'. This makes both what's shown to the user and what should be inputted to be the same and unambiguous.
=> WIP: fix: use ascii names and custom map

src/lib/http/middleware/error-handler.ts, src/lib/http/middleware/validate.ts, src/measurement/runner.ts, test/tests/integration/measurement/create-measurement.test.ts, test/tests/unit/middleware/validate.test.ts
Updated /POST "measurement" validation error to send 400, like on other endpoints.
Updated "No suitable probes found" error code to 422. It is annoying to get 400 both for validation and no probes during usage/dev/test.
Fixes #208
=> fix: validation http codes

package.json, src/lib/ws/server.ts, src/probe/route/get-probes.ts, src/probe/router.ts, test/tests/integration/measurement/create-measurement.test.ts, test/tests/unit/probe/router.test.ts, test/utils/http.ts
- fixes https://github.com/jsdelivr/globalping/issues/244
- adds node memory limits according to our current server set up.
=> Add 200ms cache to fetchSockets method

src/lib/geoip/client.ts, src/lib/geoip/whitelist.ts, src/lib/server.ts
Currently API is reading 'whitelist-ips.txt' file on every connection of probe. In the PR we are caching content in a JS Set.
=> Cache whitelist ips in memory

README.md, docs/README.md, docs/measurement/post-create.md, docs/measurement/schema/response.md, docs/probes/get.md
Some urls in the docs have a "/" at the end when it shouldn't and therefore it doesn't work.
=> docs: remove trailing "/" in urls

docs/measurement/get.md
In the docs there is a link to a wrong filename. Edited to point to the right file.
=> docs: fix link in docs to the right file

.mocharc.json, package-lock.json, package.json, src/probe/builder.ts, test/tests/unit/probe/router.test.ts, tsconfig.json, wallaby.js
Resolves https://github.com/jsdelivr/globalping/issues/262 .
Additionally:
- adds wallaby.js support
- updates router.test.ts to use probe data builder from source code, instead of utility one
=> feat: esm mocking

src/lib/metrics.ts, src/lib/ws/gateway.ts, src/lib/ws/server.ts
Part of #124 
It was measured that average socket.io ping-pong time is ~100ms.
Highest value for the minute vary from 1700ms to 3700ms.
=> feat: update socketio-timeouts

public/probes.vue.js, src/probe/types.ts
Part of https://github.com/jsdelivr/globalping/issues/52
=> feat: show non-ready probes first on the API page

src/lib/http/server.ts
Turns out the problem wasn't brotli directly but a bad default, which had already been fixed, but there hasn't been a new release yet: https://github.com/koajs/compress/issues/179
On level 5, the performance is comparable to gzip 6 and compression is better.
=> fix: reenable brotli on level 5

src/lib/http/server.ts
Brotli 4 is almost twice as fast and since we expect the GET endpoint to be called often, prioritizing performance makes more sense here. Gzip level is also reduced to roughly match the brotli speed. Deflate isn't really used these days so rather than testing it too I just disabled it.
=> fix: reduce compression levels

.gitignore, config/default.cjs, src/lib/ip-ranges.ts, src/lib/malware/domain.ts, src/lib/malware/ip.ts, src/lib/ws/server.ts, src/measurement/route/get-measurement.ts, src/measurement/runner.ts, src/measurement/store.ts, src/measurement/types.ts, test/tests/integration/health/health.test.ts, test/tests/integration/measurement/create-measurement.test.ts, test/tests/integration/measurement/probe-communication.test.ts, test/tests/integration/measurement/timeout-result.test.ts, test/tests/integration/middleware/compress.test.ts, test/tests/integration/middleware/cors.test.ts, test/tests/integration/middleware/domain-redirect.test.ts, test/tests/integration/middleware/etag.test.ts, test/tests/integration/middleware/ratelimit.test.ts, test/tests/integration/middleware/responsetime.test.ts, test/tests/integration/probes/get-probes.test.ts, test/tests/unit/measurement/runner.test.ts, test/tests/unit/measurement/store.test.ts, test/tests/unit/ws/server.test.ts
- fixes https://github.com/jsdelivr/globalping/issues/318
- sets `fetchSocketsCacheTTL` to 1000ms
Note: data migration or flush of db is required as old measurent results will be returned as object instead of array.
=> feat: optimize GET operations

src/index.ts, src/probe/builder.ts, src/probe/sockets-location-filter.ts, src/probe/types.ts, test/tests/unit/probe/router.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/247 and https://github.com/jsdelivr/globalping/issues/334
=> feat: ignore partial matches after exact match in magic field

src/measurement/schema/location-schema.ts
The custom function isn't actually called when combined with explicit `valid()` and it isn't needed for those fields anyway.
=> fix: remove useless normalization

src/lib/geoip/client.ts, test/tests/unit/geoip.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/388
At the time of the issue redis was in a strange state, it was rejecting all the queries (GET, SET, etc.). Our geo ip logic uses redis to get cached value before making real requests to the 3rd party geo APIs. Since get command was throwing errors the whole geo ip function was throwing and API were unable to get the geo ips of probes and sent `unresolvable geoip` to them.
Probes were constantly reconnecting when API was down. But they stopped reconnecting after getting `unresolvable geoip` error from the API, which is valid behaviour from the perspective of the probe.
In that fix we are catching any geo ip redis errors and making request to the 3rd party geo APIs not only if there is no value in the cache but also if the cache itself …
=> fix: make geoip client work even if redis is broken

docs/CLIENT_GUIDELINES.md, package-lock.json, package.json, probes-stats/known.ts, public/v1/spec.yaml, src/index.ts, src/lib/http/middleware/default-json.ts, src/lib/http/middleware/error-handler.ts, src/lib/http/middleware/ratelimit.ts, src/lib/http/middleware/validate.ts, src/lib/http/server.ts, src/measurement/runner.ts, test/plugins/oas/index.js, test/tests/contract/portman-config.json, test/tests/integration/measurement/create-measurement.test.ts, test/tests/integration/measurement/probe-communication.test.ts, test/tests/integration/measurement/timeout-result.test.ts, test/tests/integration/middleware/ratelimit.test.ts, test/tests/integration/probes/get-probes.test.ts, test/tests/unit/middleware/error-handler.test.ts, test/tests/unit/middleware/ratelimit.test.ts, test/tests/unit/middleware/validate.test.ts
- Adds docs in OpenAPI format, which will be rendered at https://www.jsdelivr.com/docs/api.globalping.io. After it's live, the MD docs can be deleted.
- The docs can be previewed locally by setting up the website project and overriding [this option](https://github.com/jsdelivr/www.jsdelivr.com/blob/743d51182d8edd90e1e3d4ea3d1ebb6153aaea44/config/default.js#L11) to the local API instance.
- All integration tests were updated to validate schemas. In some cases, there were minor mistakes in the tests, which were fixed.
- Slightly tweaked error messages for consistency.
=> Add OpenAPI docs and tests

package-lock.json, package.json, src/lib/private-ip.ts, src/measurement/schema/utils.ts, src/probe/builder.ts
The PR replaces the `private-ip` npm package with Node.js built-in native API.
The `net.BlockList` API is first introduced in Node.js 14.18.0 and 15.0.0, 
and its API doc can be found here: https://nodejs.org/dist/latest-v18.x/docs/api/net.html#class-netblocklist.
The `net.BlockList` API is originally designed for the purpose of disabling inbound or outbound access to specific IP addresses, IP ranges, or IP subnets. However, it is also a high-performance IP List and can check whether an IP address is included in the list.
The PR creates a `net.BlockList` instance and adds every known private IP range to the list.
=> Refactor: replace `private-ip` with Node.js native API

src/lib/geoip/city-approximation.ts, src/lib/ws/helper/probe-ip-limit.ts, src/lib/ws/helper/reconnect-probes.ts, src/lib/ws/helper/throttle.ts, src/lib/ws/server.ts, test/tests/unit/ws/server.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/404.
I've checked the code on a remote dev env (https://github.com/jsdelivr/globalping/issues/418). Performance is the same as for current master, so PR is not adding extra load.
=> fix: disable throttling for probe ip limit fetchSockets

config/init.sql, docker-compose.yml, docs/geoip.md, src/lib/adopted-probes.ts, test/tests/unit/adopted-probes.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/428
=> feat: sync adopted probe data

src/probe/builder.ts, src/probe/route/get-probes.ts, src/probe/types.ts, test/tests/integration/probes/get-probes.test.ts, test/tests/unit/adopted-probes.test.ts, test/tests/unit/ws/fetch-sockets.test.ts, test/utils/server.ts
Fixes https://github.com/jsdelivr/globalping-probe/issues/193
=> feat: add new admin vars

probes-stats/known-probes.json, probes-stats/known.ts, src/adoption-code/route/adoption-code.ts, src/index.ts, src/lib/http/middleware/is-system.ts, src/lib/http/server.ts, src/lib/metrics.ts, src/lib/ratelimiter.ts, src/lib/redis/persistent-client.ts, src/lib/redis/scripts.ts, src/lib/server.ts, src/measurement/store.ts, src/probe/route/get-probes.ts, test/setup.ts, test/tests/integration/adoption-code.test.ts, test/tests/integration/probes/get-probes.test.ts, test/tests/unit/index.test.ts, test/tests/unit/measurement/store.test.ts, test/tests/unit/middleware/is-system.test.ts, wallaby.js
Part of https://github.com/jsdelivr/globalping/issues/452
=> feat: add extra info to /probes if systemkey provided

src/lib/ratelimiter.ts, test/tests/integration/ratelimit.test.ts
Before: 
1. The user has 3 credits remaining and makes a request for 5 locations.
2. The request fails, and **the user has 0 credits remaining.**
After:
1. The user has 3 credits remaining and makes a request for 5 locations.
2. The request fails, and **the user still has 3 credits remaining.**
=> fix: improve rate limit handling when near zero

.github/workflows/ci.yml, .gitignore, config/redis.conf, docker-compose.yml, package.json, src/index.ts, src/lib/flush-redis-cache.ts, src/lib/get-probe-ip.ts, test/tests/unit/index.test.ts, wallaby.js
Fixes https://github.com/jsdelivr/globalping/issues/472
Additionally:
- update get-fake-ip logic so it doesn't change ip after probe reconnects;
- change redis image to the one that supports arm64 architecture. Previous was unstable on my new mac;
- change redis image in ci to make sure tests are passing with only reJSON module.
=> feat: flush redis only on deploys but not on regular restarts

src/lib/geoip/city-approximation.ts, src/lib/metrics.ts, src/lib/redis/client.ts, src/lib/redis/measurement-client.ts, src/lib/redis/persistent-client.ts, src/lib/redis/scripts.ts, src/lib/redis/shared.ts, src/lib/server.ts, src/measurement/store.ts, test/tests/unit/index.test.ts, test/tests/unit/measurement/store.test.ts
1. Moves the measurement data to their own DB to take advantage of the fact that redis [maintains key count separately for each DB](https://redis.io/commands/dbsize/). This allows us to drop the slower SCAN iteration approach.
2. Updates the measurement count calculation to account for the fact that one measurement uses 2 (when finished) or 3 (when running) keys.
=> perf: separate measurement data for fast key counting

src/probe/probes-location-filter.ts, test/tests/unit/probe/router.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/505
Recalculation of ratio breaks when groups are not full. E.g. there are 3 locations (A: 100 probes avaliable, B: 10 probes available, C: 100 probes available) and 60 probes required. A picks 60/3=20, then B picks 10 (only 10 are available), then for C it is (60-30)/1=30. So we end up with 20/10/30. Instead it should be 25/10/25. So in PR we are recalculating ratio when all locations are handled once.
=> feat: select locations more evenly

src/lib/rate-limiter.ts, src/lib/redis/client.ts, src/lib/redis/measurement-client.ts, src/lib/redis/persistent-client.ts, src/lib/redis/shared.ts, src/lib/ws/server.ts, src/lib/ws/synced-probe-list.ts, test/dist.js, test/tests/unit/ws/server.test.ts, test/tests/unit/ws/synced-probe-list.test.ts
#501 overall improved the performance of the app but resulted in a *higher* redis load than expected. Most likely, it was because the previous pull-based mechanism only exchanged data when the instance was active (there was a request that needed the data), while the new sync runs all the time (as if there was at least one request every second on each instance) - so theoretically, the new approach was more efficient, but only in high-load scenarios.
This PR further improves the sync by storing the data in redis and only notifying other instances when there are changes (detected per-probe; similar idea previously suggested in https://github.com/jsdelivr/globalping/issues/419#issuecomment-1711557404), which reduces the size (not number, because of "keep alive") of exchanged messages. 
I …
=> perf: reduce data sent in probe sync

.deepsource.toml
Our own linter works better and deepsource doesn't bring anything extra, it's just annoying.
=> ci: disable deepsource for JS

.github/workflows/ci.yml, .github/workflows/e2e.yml, config/create-dbs.sql, config/default.cjs, config/test.cjs, docker-compose.yml, test/e2e/cases/dns.test.ts, test/e2e/cases/http.test.ts
To avoid conflicts with the other DB that will be used for the jsDelivr part.
=> refactor: rename dash DB

public/v1/components/headers.yaml, public/v1/components/responses.yaml, src/lib/rate-limiter.ts, test/tests/integration/ratelimit.test.ts
Removes `X-Credits-Required`, which was confusing because it didn't cover the whole request cost (depending on the hourly rate limit status). Instead, there are now two headers:
- `X-Request-Cost` - the total cost of the request, always present,
- `X-RateLimit-Consumed` - part of the request cost that was paid by rate limit points (mirrors the existing `X-Credits-Consumed`).
=> feat: improve credits-related headers

config/default.cjs, config/development.cjs, src/lib/http/middleware/cors.ts, src/measurement/route/create-measurement.ts, test/tests/integration/middleware/cors.test.ts
Required for #539 to work as cookies are not allowed by default for CORS requests.
=> fix: allow credentials for trusted CORS requests

.mocharc.e2e.cjs, .mocharc.json, migrations/create-tables.js.sql, src/lib/http/auth.ts, src/lib/http/middleware/authenticate.ts, src/lib/http/middleware/cors.ts, src/lib/http/middleware/default-json.ts, src/lib/redis/client.ts, src/lib/redis/measurement-client.ts, src/lib/redis/persistent-client.ts, src/lib/redis/subscription-client.ts, src/measurement/route/create-measurement.ts, src/types.d.ts, test/tests/integration/middleware/authenticate.test.ts, test/tests/integration/ratelimit.test.ts, test/tests/unit/auth.test.ts
Part of https://github.com/jsdelivr/globalping-auth/pull/1
Minimal changes here, the first 4 commits are unrelated fixes. The auth changes are:
- check for `type: 'access_token'`,
- loading scopes, though these are not used anywhere, as all tokens get exactly the same scope.
=> feat: OAuth support

config/default.cjs, config/test.cjs, public/v1/components/headers.yaml, public/v1/components/responses.yaml, public/v1/spec.yaml, src/lib/rate-limiter/rate-limiter-get.ts, src/lib/rate-limiter/rate-limiter-post.ts, src/limits/route/get-limits.ts, src/measurement/route/get-measurement.ts, src/measurement/runner.ts, test/e2e/cases/limits.test.ts, test/tests/integration/limits.test.ts, test/tests/integration/ratelimit.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/526
=> feat: rate limits for GET

public/v1/components/schemas.yaml, src/lib/http/auth.ts, src/lib/http/middleware/authenticate.ts, src/lib/rate-limiter/rate-limiter-post.ts, src/probe/probes-location-filter.ts, test/tests/integration/measurement/create-measurement.test.ts, test/tests/integration/ratelimit.test.ts, test/tests/unit/auth.test.ts, test/utils/server.ts
Part of https://github.com/jsdelivr/globalping/issues/547
=> feat: anonymous tokens

src/probe/probes-location-filter.ts
In the extreme case of using 128 combined conditions in `magic`, this brings the matching time from about 150 ms to about 10 ms. The repeated `replaceAll()` calls were very slow.
=> perf: make magic matching faster

src/lib/malware/client.ts, src/measurement/schema/command-schema.ts, src/measurement/schema/location-schema.ts, test/tests/unit/measurement/schema/schema.test.ts
To match the format Joi generates for its own errors.
=> misc: unify the format of validation error messages

src/lib/override/adopted-probes.ts, test/tests/unit/override/adopted-probes.test.ts
Part of: https://github.com/jsdelivr/globalping-dash-directus/issues/33
=> feat: move deletion of expired adoptions to the dashboard BE

src/lib/override/adopted-probes.ts, test/tests/unit/override/adopted-probes.test.ts
Most likely as a result of https://github.com/jsdelivr/globalping-dash-directus/commit/ce54f8e61bec9faf5fb988ee49a329f05eacc47b, the sync is now failing with this error:
```
update `gp_adopted_probes` set `ip` = 'xxx', `altIps` = '[\"yyy\"]', `uuid` = 'zzz' where `ip` = 'xxx' - ER_DUP_ENTRY: Duplicate entry 'zzz' for key 'gp_adopted_probes_uuid_unique'
```
To avoid it, we must either not try to update the UUID without changing its value, or include the value in the WHERE part as well.
=> fix: update UUID only if it changed

migrations/create-tables.js.sql, src/lib/override/adopted-probes.ts, test/tests/unit/override/adopted-probes.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/572
What it does:
- in case of duplication error, extra adoptions are deleted, then update repeats;
- individual sync errors are logged and resolved, not to break syncing of others;
- uuid equality check is removed as not required.
=> fix: adopted probes sync issue

probes-stats/known.ts, src/lib/alt-ips.ts, src/lib/geoip/client.ts, src/lib/geoip/fake-client.ts, src/lib/geoip/providers/fastly.ts, src/lib/geoip/providers/ip2location.ts, src/lib/geoip/providers/ipinfo.ts, src/lib/geoip/providers/ipmap.ts, src/lib/geoip/providers/maxmind.ts, src/lib/get-probe-ip.ts, src/probe/builder.ts, test/mocks/nock-geoip.json, test/tests/integration/alternative-ip.test.ts, test/tests/unit/alt-ips.test.ts, test/tests/unit/geoip/client.test.ts, test/tests/unit/probe/router.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/576
Notes:
- During deploys number of geoip requests will double (we have 1300 primary ips + ~1300 alt ips). Need to check our limits.
=> feat: filter incoming alt IPs

src/lib/http/middleware/authenticate.ts, src/lib/metrics.ts, src/lib/override/adopted-probes.ts, src/measurement/runner.ts, src/probe/types.ts
Part of #577. Adds:
- user info when creating measurements,
- measurement id, type, and target labels,
- active probes metrics.
=> misc: add APM annotations and more metrics

public/demo/globals.js, public/v1/components/schemas.yaml, src/measurement/schema/command-schema.ts, src/measurement/types.ts, test/e2e/cases/http.test.ts, test/tests/unit/measurement/schema/schema.test.ts, wallaby.e2e.js, wallaby.js
Fixes https://github.com/jsdelivr/globalping-probe/issues/261
E2E should pass after the merge of https://github.com/jsdelivr/globalping-probe/pull/265
=> feat: add OPTIONS as an allowed HTTP Method

docs/geoip.md, src/lib/geoip/client.ts, test/tests/unit/geoip/client.test.ts
Sometimes, we run into a case where we get multiple cities that are different but close to each other, and then one somewhere far, reported by two providers, e.g.:
```
lisbon, PT
san francisco, US
san jose, US
new york, US
lisbon, PT
```
```
johannesburg, ZA
amsterdam, NL
lelystad, NL (almost amsterdam)
amsterdam, NL
johannesburg, ZA
```
Sometimes each provider returns a different city, but multiple agree on the country:
```
calais, FR
Paris, FR
brugge, BE
roubaix, FR
```
We currently don't consider at all how close or far the cities are, and doing so makes sense and does improve the results a little.   I initially considered clustering the cities by distance based on coordinates, but this is easier and seems to work just as well.
=> feat: only consider cities from the most likely country

migrations/create-tables.js.sql, src/lib/override/adopted-probes.ts, test/tests/unit/override/adopted-probes.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/541
=> feat: mark user owned probes in API responses

src/lib/probe-validator.ts, src/lib/ws/gateway.ts, src/measurement/handler/ack.ts, src/measurement/handler/progress.ts, src/measurement/handler/request.ts, src/measurement/handler/result.ts, src/measurement/runner.ts, src/measurement/store.ts, src/measurement/types.ts, test/tests/integration/measurement/create-measurement.test.ts, test/tests/unit/measurement/store.test.ts, test/tests/unit/probe-validator.test.ts
Fixes https://github.com/jsdelivr/meta/issues/51
Didn't add it as a part of lua script, as global hash structure is used. Plus checks are mostly performed in-memory, redis is a fallback.
=> feat: update message handling

src/adoption/adoption-token.ts, src/lib/override/adopted-probes.ts, src/probe/builder.ts, src/probe/router.ts, src/probe/types.ts, test/tests/integration/adoption-code.test.ts, test/tests/integration/adoption-token.test.ts, test/tests/unit/override/adopted-probes.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/625
Adding logic of matching by token+offline+asn+city here as well to prevent a possible race condition, where sync in `adopted-probes.ts` happens before `/adopt-by-token` is handled, so new probe is created in db instead of updating of the offline probe.
=> feat: adopt user's offline probe by asn+city if possible

src/probe/probes-location-filter.ts
#637 improved the situation significantly for ASNs, but cities still repeat in the results quite a lot. This is expected and not entirely avoidable, but we can improve it somewhat by boosting less common cities within their own ranking group. E.g.:
- 30 probes in City1, ASN1,
- 10 probes in City1, ASN2,
- 5 probes in City1, ASN3,
- 5 probes in City2, ASN4,
- 4 probes in City3, ASN5
We boost the last two groups above the third one, as they all rank the same, but the last two increase city diversity while the third one doesn't.
Difference on our real data for Germany (in both cases the results could vary a bit between runs):
```
limit 10 - before
[
[ 'DE, Frankfurt', 6 ],
[ 'DE, Nuremberg', 2 ],
[ 'DE, Berlin', 1 ],
[ 'DE, Falkenstein', 1 ]
]
limit 10 - after
[
[ 'DE, Frankfurt', 4 ],
[ …
```
=> feat: improve diversification across cities

public/demo/globals.js, public/v1/components/schemas.yaml, src/measurement/schema/command-schema.ts, src/measurement/types.ts
Fixes #615
See https://github.com/jsdelivr/globalping-probe/pull/287 for changes to probe.
I tested this with the local dev setup.
=> feat: support svcb records for dns requests

src/lib/geoip/utils.ts, src/lib/override/adopted-probes.ts, src/measurement/runner.ts, src/probe/builder.ts, src/probe/probes-location-filter.ts, src/probe/router.ts, src/probe/types.ts, test/tests/integration/measurement/probe-communication.test.ts, test/tests/unit/override/adopted-probes.test.ts
1. Use a precomputed grouping key in the diversified shuffle.
2. ~~Avoid repeated `getIndexPosition()` calls by collecting the returned values the first time.~~
=> perf: optimize magic sort and diversified shuffle

src/lib/location/location.ts, test/tests/integration/measurement/create-measurement.test.ts, test/tests/unit/probe/router.test.ts
Implements the idea from https://github.com/jsdelivr/globalping/issues/383#issuecomment-3062524054. For network names, we'll consider any full-word prefix match to be "exact", e.g., for `Vodafone Czech Republic a.s.`, all of these are considered exact: `Vodafone Czech Republic a.s.`, `Vodafone Czech Republic`, `Vodafone Czech`, `Vodafone`.
This means `Vodafone` will match all national entities and legal forms, even if a probe with just `Vodafone` network exists.
=> feat: prefix-based network matching in magic mode

src/lib/geoip/legal-name-normalization.ts, test/tests/unit/geoip/legal-name-normalization.test.ts, wallaby.js
- result is exactly the same as with regexes for all current probes
- speed with node v22.16.0:
```
tsx normalize-from-code.js probes.json
normalizeLegalName xTom GmbH: 0.123ms
normalizeLegalName STYLISH BY A&L SRL: 0.059ms
normalizeLegalName HostPapa: 0.007ms
normalizeLegalName HostPapa: 0.003ms
normalizeLegalName Odido Netherlands B.V.: 0.01ms
normalizeLegalName Odido Netherlands B.V.: 0.008ms
normalizeLegalName Eons Data Communications Limited: 0.068ms
normalizeLegalName AkileCloud Network: 0.011ms
normalizeLegalName GLOBAL INTERNET SOLUTIONS LLC: 0.009ms
normalizeLegalName Oracle Corporation: 0.004ms
normalizeLegalName Terabix: 0.006ms
normalizeLegalName Hetzner Online GmbH: 0.004ms
...
```
=> perf: use Sets instead of RegExes in normalizeLegalName
