src/lib/malware/client.ts, src/lib/malware/domain.ts, src/lib/malware/ip.ts, src/lib/server.ts, test/tests/unit/malware.test.ts, test/utils/malware.ts
=> ref: keep malware data in memory

docs/measurement/post-create.md, docs/measurement/schema/request.md, public/measurements.vue.js, src/measurement/runner.ts, src/measurement/schema/command-schema.ts, src/measurement/schema/global-schema.ts, src/measurement/schema/utils.ts, src/measurement/types.ts, test/tests/integration/measurement/create-measurement.test.ts, test/tests/unit/measurement/schema.test.ts
=> ref: post schema update

docs/measurement/post-create.md, docs/measurement/schema/request.md, docs/measurement/schema/response.md, public/measurements.vue.js, src/measurement/schema/command-schema.ts, test/tests/unit/measurement/schema.test.ts
=> ref: HTTP schema + docs fix

src/probe/builder.ts
=> fix: raplace ^ with >= check

src/measurement/schema/location-schema.ts, test/tests/unit/measurement/schema.test.ts
=> ref: normalize input values

src/measurement/store.ts
resolve #192 
until we figure out what to do with #193
=> ref: measurement/store: isolated connections

src/lib/ws/helper/probe-ip-limit.ts, src/lib/ws/middleware/probe-metadata.ts, src/lib/ws/ws-error.ts
```
[2022-08-22 13:40:59] [DEBUG] [2442224] [ws:error] unresolvable geoip
info -> {"socketId":"m9NhJAMPkkaHjCjeAAAH","ipAddress":"::ffff:127.0.0.1"}
stack -> Error: unresolvable geoip
```
=> ref: attach IP address to WS error

src/measurement/schema/command-schema.ts, src/measurement/schema/utils.ts, test/tests/unit/measurement/schema.test.ts
=> fix: allow underscores in target schema

src/lib/get-probe-ip.ts, src/lib/http/error-handler.ts, src/lib/ws/helper/error-handler.ts, src/lib/ws/helper/subscribe-handler.ts, src/lib/ws/middleware/probe-metadata.ts, src/probe/builder.ts
https://github.com/jsdelivr/globalping/issues/219
=> fix #219: remove empty IPv6 prefix from probes ips

src/lib/ws/helper/reconnect-probes.ts, src/lib/ws/server.ts, test-perf/artillery.yml, test-perf/index.ts, test/tests/unit/geoip.test.ts, test/tests/unit/ws/server.test.ts
Closes https://github.com/jsdelivr/globalping/issues/237
=> feat: reconnect all probes after start of the instance

src/probe/route/get-probes.ts, test/tests/integration/probes/get-probes.test.ts
Misspelling of latitude
https://en.wikipedia.org/wiki/Latitude
=> Fix typo in get-probes.ts

public/globals.js, public/measurements.vue.js
Add ability to filter by tags from /demo page.
=> Tags on demo page

src/measurement/runner.ts, src/measurement/store.ts
=> fix: ignore all updates after measurement finished

docs/measurement/get.md, docs/measurement/post-create.md, docs/measurement/schema/response.md, docs/probes/get.md
=> docs: fix typos

src/measurement/schema/command-schema.ts, test/tests/unit/measurement/schema.test.ts
=> feat: allow hostnames as dns resolvers

.mocharc.json, package-lock.json, package.json, src/probe/builder.ts, src/probe/router.ts, src/probe/sockets-location-filter.ts, test/tests/integration/measurement/create-measurement.test.ts, test/tests/unit/probe/router.test.ts, tsconfig.json, wallaby.js
Resolves https://github.com/jsdelivr/globalping/issues/247
=> feat: smarter magic field

docs/measurement/get.md, docs/measurement/schema/response.md, package-lock.json, package.json, src/measurement/runner.ts, src/measurement/store.ts, src/measurement/types.ts
Adds status to the result field of the probe measurement. Possible values are: in-progress, finished, and failed.
Probe part is here: https://github.com/jsdelivr/globalping-probe/pull/108
Part of #212
=> feat: add measurement statuses

config/default.cjs, config/test.cjs, package-lock.json, package.json, src/lib/ws/server.ts
- should fix https://github.com/jsdelivr/globalping/issues/302
- runs at most one concurrent fetchSockets if that operation takes more than cache TTL
=> fix: run at most one concurrent fetchSocket operation

src/measurement/handler/ack.ts, src/measurement/route/create-measurement.ts, src/measurement/runner.ts, src/measurement/store.ts, src/measurement/types.ts, test/tests/integration/measurement/probe-communication.test.ts
=> feat: save initial result objects as one redis command

test/tests/integration/measurement/timeout-result.test.ts, test/tests/unit/measurement/store.test.ts, test/utils/server.ts
=> test: add test for timeout of the measurement

src/lib/http/error-handler.ts
Fix https://github.com/jsdelivr/globalping/issues/311
=> feat: ignore econnreset errors in newrelic

.gitignore, src/lib/ip-ranges.ts, src/lib/malware/domain.ts, src/lib/malware/ip.ts
Fixes https://github.com/jsdelivr/globalping/issues/320
=> feat: move generated files to `data` folder

.gitignore, src/lib/ip-ranges.ts, src/lib/malware/domain.ts, src/lib/malware/ip.ts, src/lib/ws/server.ts, test/tests/integration/health/health.test.ts, test/tests/integration/measurement/create-measurement.test.ts, test/tests/integration/measurement/probe-communication.test.ts, test/tests/integration/measurement/timeout-result.test.ts, test/tests/integration/middleware/compress.test.ts, test/tests/integration/middleware/cors.test.ts, test/tests/integration/middleware/domain-redirect.test.ts, test/tests/integration/middleware/etag.test.ts, test/tests/integration/middleware/ratelimit.test.ts, test/tests/integration/middleware/responsetime.test.ts, test/tests/integration/probes/get-probes.test.ts, test/tests/unit/ws/server.test.ts
fix tests skipped during https://github.com/jsdelivr/globalping/pull/325
=> test: fix skipped ws server test

src/lib/metrics.ts, src/lib/redis/client.ts, src/lib/redis/scripts.ts, test/tests/integration/measurement/timeout-result.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/312
=> feat: use lua script to count measurements in redis

docs/measurement/get.md, docs/measurement/schema/response.md, src/measurement/runner.ts, src/measurement/schema/command-schema.ts, src/measurement/schema/global-schema.ts, src/measurement/schema/location-schema.ts, src/measurement/schema/utils.ts, src/measurement/store.ts, src/measurement/types.ts, test/tests/unit/measurement/runner.test.ts, test/tests/unit/measurement/schema/schema.test.ts, test/tests/unit/measurement/store.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/348
=> feat: add measurement request data to the response object

src/measurement/handler/progress.ts, src/measurement/runner.ts, src/measurement/store.ts, src/measurement/types.ts, test/tests/unit/measurement/store.test.ts
Part of https://github.com/jsdelivr/globalping-probe/issues/137
=> feat: process rawHeaders and rawBody fields inside http in-progress updates

src/probe/sockets-location-filter.ts, test/tests/unit/probe/router.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/185
=> fix: fix incorrect probes count

src/lib/redis/client.ts, src/lib/redis/scripts.ts, src/measurement/runner.ts, src/measurement/store.ts, test/tests/unit/measurement/runner.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/343
=> feat: use lua script to store measurement results

src/lib/location/continents.ts, src/lib/location/location.ts, src/lib/location/regions.ts, src/probe/builder.ts, test/tests/unit/probe/router.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/361
=> feat: add aliases to continents and regions

docs/measurement/post-create.md
Fixed a syntax error in the JSON request body example.
=> Fixed JSON example

docs/measurement/post-create.md
=> Remove docs mistake

src/lib/metrics.ts
Fixes https://github.com/jsdelivr/globalping/issues/380
=> fix: fix reported probes count

.gitignore, package-lock.json, package.json
Fixes https://github.com/jsdelivr/globalping/issues/387
=> feat: update newrelic version

src/lib/ws/gateway.ts, src/lib/ws/helper/error-handler.ts, src/lib/ws/helper/probe-ip-limit.ts, src/lib/ws/middleware/probe-metadata.ts, src/lib/ws/ws-error.ts, src/probe/builder.ts, test/tests/unit/ws/error-handler.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/390
=> feat: refactor error message api-probe communication

config/test.cjs, package-lock.json, package.json, src/lib/ws/helper/throttle.ts, src/lib/ws/server.ts, test/tests/integration/measurement/timeout-result.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/368
=> feat: update fetchSockets caching algorithm

wallaby.js
Fix wallaby configuration to work with chai plugins.
=> fix: fix wallaby configuration

src/lib/geoip/client.ts, src/lib/geoip/providers/fastly.ts, src/lib/geoip/providers/ip2location.ts, test/mocks/nock-geoip.json, test/tests/unit/geoip.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/399
=> feat: use ip2location as vpn detection provider

newrelic.cjs
Fixes https://github.com/jsdelivr/globalping/issues/391
=> fix: send fewer transaction samples to newrelic

public/demo/index.html, public/demo/probes.vue.js, src/probe/builder.ts, src/probe/route/get-probes.ts, src/probe/types.ts, test/tests/integration/measurement/probe-communication.test.ts, test/utils/server.ts
Fixes https://github.com/jsdelivr/globalping-probe/issues/168
=> feat: store probe node version

src/lib/geoip/client.ts, src/lib/internal-error.ts, src/lib/probe-error.ts, src/lib/ws/helper/probe-ip-limit.ts, src/lib/ws/middleware/probe-metadata.ts, src/probe/builder.ts
Part of https://github.com/jsdelivr/globalping/issues/417
=> refactor: rename internal error to probe error

newrelic.cjs
Fixes https://github.com/jsdelivr/globalping/issues/391
=> feat: send less tracing data to newrelic

probes-stats/known-probes.json, probes-stats/known.ts, src/index.ts, src/lib/metrics.ts, src/lib/ratelimiter.ts, src/lib/redis/client.ts, src/lib/redis/persistent-client.ts, src/lib/redis/scripts.ts, src/lib/server.ts, src/measurement/store.ts, test/setup.ts, test/tests/unit/index.test.ts, test/tests/unit/measurement/store.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/456
=> feat: split redis use to persistent and non-persistent part

src/probe/probes-location-filter.ts, test/tests/integration/measurement/create-measurement.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/462
=> fix: filter by world in any case

config/default.cjs, config/test.cjs, src/lib/cache/cache-interface.ts, src/lib/cache/null-cache.ts, src/lib/cache/redis-cache.ts, src/lib/geoip/client.ts, test/tests/integration/adoption-code.test.ts, test/tests/integration/health.test.ts, test/tests/integration/measurement/create-measurement.test.ts, test/tests/integration/measurement/probe-communication.test.ts, test/tests/integration/measurement/timeout-result.test.ts, test/tests/integration/middleware/compress.test.ts, test/tests/integration/probes/get-probes.test.ts, test/tests/integration/ratelimit.test.ts, test/tests/unit/geoip/client.test.ts, test/tests/unit/redis-cache.test.ts, test/utils/server.ts
my new laptop executes tests quicker, which broke some of the cases. Updates made:
- disable redis cache for tests instead of 1 ms ttl
- disconnect fake probes from the server side, instead of client side
- other small fixes
=> refactor: tests stabilization

src/lib/flush-redis-cache.ts
- ignore the missing file in non-prod envs
- always purge in non-prod envs (as was the case before)
=> fix: don't require a commit hash file in dev runs

config/default.cjs, src/lib/http/middleware/validate.ts, src/lib/malware/client.ts, src/measurement/schema/command-schema.ts, src/measurement/schema/global-schema.ts, src/measurement/schema/location-schema.ts, test/tests/unit/measurement/schema/schema.test.ts, wallaby.js
Fixes https://github.com/jsdelivr/globalping/issues/487
=> Refactor limits

src/lib/adopted-probes.ts, src/lib/get-probe-ip.ts, src/lib/ws/fetch-sockets.ts
Part of https://github.com/jsdelivr/dashboard/issues/26
=> fix: probe adoption issue

src/lib/server.ts, src/lib/ws/helper/probe-ip-limit.ts, src/lib/ws/server.ts, src/probe/builder.ts, test/tests/unit/ws/probe-ip-limit.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/502
=> feat: periodic ip limit check

.github/workflows/ci.yml, .github/workflows/e2e.yml, config/development.cjs, config/test.cjs, docker-compose.yml
To reduce conflicts with other projects when running locally.
=> refactor: remap ports

migrations/create-tables.js.sql, src/adoption-code/route/adoption-code.ts, src/lib/override/adopted-probes.ts, test/e2e/cases/adopted-probes.test.ts, test/tests/integration/adoption-code.test.ts, test/tests/integration/measurement/create-measurement.test.ts, test/tests/integration/measurement/probe-communication.test.ts, test/tests/integration/probes/get-probes.test.ts, test/tests/unit/override/adopted-probes.test.ts
Part of https://github.com/jsdelivr/globalping-probe/issues/171
=> feat: send node version to dashboard

public/v1/components/examples.yaml, public/v1/components/schemas.yaml
Fixes https://github.com/jsdelivr/globalping/issues/500
e2e tests should pass after merge of https://github.com/jsdelivr/globalping-probe/pull/210
=> feat: extra TLS data

src/lib/ws/synced-probe-list.ts, src/probe/builder.ts, src/probe/route/get-probes.ts, src/probe/types.ts, test/tests/integration/probes/get-probes.test.ts, test/tests/unit/override/adopted-probes.test.ts, test/tests/unit/ws/synced-probe-list.test.ts, test/utils/server.ts
Part of https://github.com/jsdelivr/globalping-probe/pull/234
=> feat: add memory and disk space reporting

package-lock.json, package.json, src/lib/http/auth.ts, test/tests/integration/middleware/authenticate.test.ts, test/tests/integration/ratelimit.test.ts, test/tests/unit/auth.test.ts
Part of https://github.com/jsdelivr/globalping-dash-directus/issues/5
=> refactor: use base32 for tokens

migrations/create-tables.js.sql, src/adoption-code/route/adoption-code.ts, src/lib/override/adopted-probes.ts, test/tests/integration/adoption-code.test.ts, test/tests/unit/override/adopted-probes.test.ts
Part of https://github.com/jsdelivr/globalping-dash/issues/25
=> feat: sync system tags with the dashboard

public/v1/components/schemas.yaml, src/probe/probes-location-filter.ts, test/tests/integration/measurement/create-measurement.test.ts, test/utils/server.ts
Fixes https://github.com/jsdelivr/globalping/issues/551
=> feat: allow user tags in magic field

src/lib/rate-limiter/rate-limiter-post.ts, test/tests/integration/ratelimit.test.ts
Updates https://github.com/jsdelivr/globalping/issues/547
=> fix: use anon rate limiter for anon tokens

.github/workflows/e2e.yml
=> ci: switch e2e tests to GH runners with CF tunnel

.github/workflows/e2e.yml, .mocharc.e2e.cjs, package.json, test/e2e/cases/dns.test.ts, test/e2e/cases/http.test.ts, test/e2e/cases/mtr.test.ts, test/e2e/cases/ping.test.ts, test/e2e/cases/traceroute.test.ts
=> test: add IPv6 e2e tests

src/lib/override/adopted-probes.ts, src/lib/override/probe-override.ts, src/lib/server.ts, src/lib/ws/server.ts, test/tests/integration/measurement/create-measurement.test.ts, test/tests/unit/override/adopted-probes.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/592
=> fix: adopted probes list should consider admin location overrides

src/lib/redis/scripts.ts
While working on #269 I noticed we're using the EVAL exactly the way we shouldn't:
> Important: to ensure the correct execution of scripts, both in standalone and clustered deployments, all names of keys that a script accesses must be explicitly provided as input key arguments. The script should only access keys whose names are given as input arguments. Scripts should never access keys with programmatically-generated names or based on the contents of data structures stored in the database.
https://redis.io/docs/latest/commands/eval/
=> fix: correctly declare keys in redis scripts

src/lib/alt-ips.ts, src/lib/redis/scripts.ts, src/measurement/store.ts, src/measurement/types.ts, test/tests/unit/measurement/store.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/600
=> feat: immutable test results if not in-progress

src/lib/alt-ips.ts, test/tests/unit/alt-ips.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/609
=> fix: duplicated alt ips on the same probe

src/lib/alt-ips.ts, src/probe/router.ts, test/tests/unit/alt-ips.test.ts, test/tests/unit/probe/router.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/604
=> fix: inconsistency in ipVersion and probe reuse handling

src/lib/alt-ips.ts, src/lib/override/adopted-probes.ts, src/probe/router.ts, test/tests/unit/alt-ips.test.ts, test/tests/unit/override/adopted-probes.test.ts, test/tests/unit/probe/router.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/610
=> feat: sync probe owner tags to the dashboard

src/probe/probes-location-filter.ts, test/tests/integration/adoption-token.test.ts
=> feat: diversify the probe selection

src/adoption/adoption-token.ts, test/tests/integration/adoption-token.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/545
=> feat: retry /adopt-by-token

migrations/create-tables.js.sql, src/lib/override/adopted-probes.ts, test/e2e/cases/adopted-probes.test.ts, test/tests/integration/adoption-token.test.ts, test/tests/unit/override/adopted-probes.test.ts
Part of https://github.com/jsdelivr/globalping-dash/issues/69
=> feat: add default tag prefix setting

public/demo/measurements.vue.js
Fixes https://github.com/jsdelivr/globalping/issues/531
=> feat: add token support to demo page

migrations/create-tables.js.sql, public/demo/measurements.vue.js, src/lib/geoip/client.ts, src/lib/geoip/fake-client.ts, src/lib/geoip/providers/fastly.ts, src/lib/geoip/providers/ip2location.ts, src/lib/geoip/providers/ipinfo.ts, src/lib/geoip/providers/ipmap.ts, src/lib/geoip/providers/maxmind.ts, src/lib/override/admin-data.ts, src/lib/override/adopted-probes.ts, src/lib/override/probe-override.ts, src/probe/builder.ts, src/probe/router.ts, src/probe/types.ts, test/e2e/cases/adopted-probes.test.ts, test/e2e/cases/probes-sync.test.ts, test/tests/integration/adoption-code.test.ts, test/tests/integration/adoption-token.test.ts, test/tests/integration/measurement/create-measurement.test.ts, test/tests/integration/measurement/probe-communication.test.ts, test/tests/integration/probes/get-probes.test.ts, test/tests/unit/geoip/client.test.ts, test/tests/unit/override/admin-data.test.ts, test/tests/unit/override/adopted-probes.test.ts
Part of https://github.com/jsdelivr/globalping-dash/issues/66
=> feat: allow probe country change

src/lib/override/adopted-probes.ts, test/tests/unit/override/adopted-probes.test.ts
=> fix: update continent and region on country change

.github/workflows/ci.yml, .github/workflows/e2e.yml, CONTRIBUTING.md, Dockerfile, docs/staging-env.md, package-lock.json, package.json, test/e2e/cases/dns.test.ts, test/e2e/cases/http.test.ts, test/e2e/cases/mtr.test.ts, test/e2e/cases/ping.test.ts, test/e2e/cases/traceroute.test.ts, test/tests/integration/alternative-ip.test.ts, tsconfig.json
Fixes https://github.com/jsdelivr/globalping/issues/657
Updating node version to v24.
=> chore: update node.js to v24

package-lock.json, package.json, src/measurement/store.ts, test/tests/unit/measurement/store.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/672
=> fix: timed out measurements stuck in "in-progress"

SUPPORTERS.md
| Supporter                                                              | Website                                             |
| :--------------------------------------------------------------------- | :-------------------------------------------------- |
| <img src="https://rarecloud.io/rarecloud.png" alt="RareCloud logo" width="150" title="RareCloud"> | [RareCloud Website](https://rarecloud.io/)         |
| <img src="https://freerangecloud.com/images/logo.png" alt="Free Range Cloud Logo" width="150" title="Free Range Cloud"> | [Free Range Cloud Website](https://freerangecloud.com/) |
| <img src="https://billing.deluxhost.net/templates/lagom2/assets/img/logo/logo_big_inverse.752041140.png" alt="Free Range Cloud Logo" width="150" title="DeluxHOST"> | [DeluxHOST …
=> docs: update SUPPORTERS.md

src/lib/http/middleware/body-parser.ts
Needed for 10e73f8befdbba3701ed4599a2a492221393783a to work.
=> fix: request body reporting

src/measurement/schema/probe-response-schema.ts
Part of https://github.com/jsdelivr/globalping-probe/issues/308
=> fix: check and possibly discard negative timings

src/lib/override/adopted-probes.ts, test/tests/unit/override/adopted-probes.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/671
=> feat: relax duplicate probe deletion requirements

src/lib/malware/domain.ts, src/lib/malware/ip.ts
=> fix: update malware ip/domain sources

test/e2e/cases/probe-logs.test.ts, test/e2e/utils.ts
=> test: add e2e tests for probe logs synchronization

src/lib/alt-ips-client.ts, src/lib/cloud-ip-ranges.ts, src/probe/builder.ts, src/probe/types.ts, test/tests/integration/measurement/create-measurement.test.ts, test/tests/integration/measurement/probe-communication.test.ts, test/tests/unit/alt-ips.test.ts, test/tests/unit/ip-ranges.test.ts, test/tests/unit/probe/router.test.ts
=> feat: add global cloud tags
